List<String> expenseCategories = [
  'Rent/Mortgage',
  'Utilities',
  'Groceries',
  'Dining Out',
  'Transportation',
  'Healthcare',
  'Entertainment',
  'Shopping',
  'Education',
  'Investments',
  'Savings',
  'Travel',
  'Debt',
  'Insurance',
  'Miscellaneous',
];
